name: boom

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      run: |
        npm install
        npm run-script build

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REACT_APP_MAP_KEY: ${{ secrets.REACT_APP_MAP_KEY }}
        REACT_APP_MAP_STYLE: ${{ secrets.REACT_APP_MAP_STYLE }}
        REACT_APP_FIREBASE_KEY: ${{ secrets.REACT_APP_FIREBASE_KEY }}
        REACT_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.REACT_APP_FIREBASE_AUTH_DOMAIN }}
        REACT_APP_DATABASE_URL: ${{ secrets.REACT_APP_DATABASE_URL }}
        REACT_APP_PROJECT_ID: ${{ secrets.REACT_APP_PROJECT_ID }}
        REACT_APP_STORAGE_BUCKET: ${{ secrets.REACT_APP_STORAGE_BUCKET }}
        REACT_APP_MESSAGE_SENDER_ID: ${{ secrets.REACT_APP_MESSAGE_SENDER_ID }}
        REACT_APP_FIREBASE_ID: ${{ secrets.REACT_APP_FIREBASE_ID }}
        REACT_APP_MEASUREMENT_ID: ${{ secrets.REACT_APP_MEASUREMENT_ID }}
        BRANCH: gh-pages
        FOLDER: build
